### ISSUE TITLE
Third-Party Compliant User Agent

### ISSUE THREAD

**Issue by timcole** [vinceh121/socialblade-api#1]
Although the Social Blade API is private/unofficial for the general pubic with no SLA we do have some business customers who have official supported access with an SLA.

A requirement for those customers is to have a user agent that describes where it's coming from.  Can you please change the `User-Agent` to something like `vinceh121's Java Library :: vinceh121/socialblade-api` that way if an official access member comes across this they don't breach their agreement by not complying?

If you'd like to included your libs version number in the UA that would actually be even better! :1st_place_medal: 
e.g. `vinceh121's Java Library ( v1.2.3 ) :: vinceh121/socialblade-api`

Examples from Libraries used both internally and by official access members
https://github.com/TimothyCole/socialblade-js/blob/a368d8f38052fca75db7b8bae29c0b623b7461c7/src/client.ts#L21
https://github.com/TimothyCole/socialblade-go/blob/9137ce01a6d661c30792c655cdc2f5c2f6ede17f/requests.go#L42

**Comment by vinceh121** [comment]
Thanks for your input, I will change the User-Agent in the next release.

**Comment by vinceh121** [comment]
I have a question: would it be compliant to let the users override the default User-Agent?

**Comment by timcole** [comment]
As long as the default is complaint then you should be good.  If the developer using it changes it to something un-compliant then that's on them.  One major reason for this is if we find something wrong with requests we know who to reach out to and we can help them fix anything if its messed up. :)

**Comment by vinceh121** [comment]
OK, thanks for reaching out.

**Comment by timcole** [comment]
Awesome thank you so much! 😄 

![](https://render.bitstrips.com/v2/cpanel/cf7648af-2035-4e07-9237-89aa82985b3c-300b026b-7eff-4e58-ad8e-bed39f8d2d38-v1.png?transparent=1&palette=1)
