### ISSUE TITLE
YouTuber not found

### ISSUE THREAD

**Issue by AriixIT** [vinceh121/socialblade-api#3]
No matter which YouTuber I search, it doesn't find it. Even pewdiepie.
![oof](https://user-images.githubusercontent.com/49060231/63428447-de0a0000-c417-11e9-96d7-850ad6e334c0.PNG)

**Comment by vinceh121** [comment]
Is the login procedure successful? Can you show your code or say what endpoint you are using?

**Comment by AriixIT** [comment]
I went through the debugger and the login was successful. I'm using the
code that you have as an example in the README.md. It fails as it tries to
return the JSON.

Vincent <notifications@github.com> schrieb am Mi., 21. Aug. 2019, 14:20:

**Comment by vinceh121** [comment]
SocialBlade seems to be restricting my API based on the User-Agent now, try to add `sb.setUserAgent("Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0")` just after the constructor and see if that fixes it

**Comment by AriixIT** [comment]
The function setUserAgent() doesn't seem to exist.

Am Mi., 21. Aug. 2019 um 15:00 Uhr schrieb Vincent <notifications@github.com

**Comment by vinceh121** [comment]
In which case you'll probably need to upgrade to the latest version (0.2.2)

**Comment by AriixIT** [comment]
Ok yeah, now it works! Thanks!

Am Mi., 21. Aug. 2019 um 15:54 Uhr schrieb Vincent <notifications@github.com

**Comment by vinceh121** [comment]
You're welcome!

**Comment by AriixIT** [comment]
The only thing I noticed, what you might could improve, is that if I search
for example for "Ariix", it doesn't work. Probably, because there exist 2
channels with this exact name. At least it returns the NOT FOUND message,
but still great work!

Am Mi., 21. Aug. 2019 um 16:07 Uhr schrieb Vincent <notifications@github.com

**Comment by vinceh121** [comment]
There isn't a way I could fix this, that's only managed on SocialBlade's part, but you could pass the channel ID instead

**Comment by AriixIT** [comment]
Okay, thanks.

Am Mi., 21. Aug. 2019 um 16:40 Uhr schrieb Vincent <notifications@github.com
